/**
  ******************************************************************************
  * @file    startup_K1921VK028.h
  * @version 1.0
  * @date:   26.03.2019
  * @brief   Заголовочный файл с векторами прерываний К1921ВК028
  *
  ******************************************************************************
  */

/*----------Macro definition-----------------------------------------------------*/
#define WEAK __attribute__ ((weak,used,alias("Default_Handler")))

/*----------Symbols defined in linker script-------------------------------------*/
extern unsigned int _sidata;    /*!< Start address for the .data section(Flash)  */
extern unsigned int _sdata;     /*!< Start address for the .data section(RAM)    */
extern unsigned int _edata;     /*!< End address for the .data section(RAM)      */
extern unsigned int _sbss;      /*!< Start address for the .bss section(RAM)     */
extern unsigned int _ebss;      /*!< End address for the .bss section(RAM)       */
extern unsigned int _estack;	/*!< End address for the stack section           */

/*----------Function prototypes--------------------------------------------------*/
extern int main(void);           	/*!< The entry point for the application.    */
extern void SystemInit(void);    	/*!< Setup the microcontroller system(CMSIS) */
static void Default_Handler(void);  /*!< Default exception handler            	 */

/*----------Declaration of the default fault handlers----------------------------*/
/*----------Core Exceptions------------------------------------------------------*/
void Reset_Handler(void);
void WEAK NMI_Handler(void);
void WEAK HardFault_Handler(void);
void WEAK MemManage_Handler(void);
void WEAK BusFault_Handler(void);
void WEAK UsageFault_Handler(void);
void WEAK SVC_Handler(void);
void WEAK DebugMon_Handler(void);
void WEAK PendSV_Handler(void);
void WEAK SysTick_Handler(void);
/*----------External Exceptions--------------------------------------------------*/
void WEAK WDT_IRQHandler(void);
void WEAK RCU_IRQHandler(void);
void WEAK RTC_IRQHandler(void);
void WEAK MFLASH_IRQHandler(void);
void WEAK BFLASH_IRQHandler(void);
void WEAK GPIOA_IRQHandler(void);
void WEAK GPIOB_IRQHandler(void);
void WEAK GPIOC_IRQHandler(void);
void WEAK GPIOD_IRQHandler(void);
void WEAK GPIOE_IRQHandler(void);
void WEAK GPIOF_IRQHandler(void);
void WEAK GPIOG_IRQHandler(void);
void WEAK GPIOH_IRQHandler(void);
void WEAK GPIOJ_IRQHandler(void);
void WEAK GPIOK_IRQHandler(void);
void WEAK GPIOL_IRQHandler(void);
void WEAK GPIOM_IRQHandler(void);
void WEAK DMA_CH0_IRQHandler(void);
void WEAK DMA_CH1_IRQHandler(void);
void WEAK DMA_CH2_IRQHandler(void);
void WEAK DMA_CH3_IRQHandler(void);
void WEAK DMA_CH4_IRQHandler(void);
void WEAK DMA_CH5_IRQHandler(void);
void WEAK DMA_CH6_IRQHandler(void);
void WEAK DMA_CH7_IRQHandler(void);
void WEAK DMA_CH8_IRQHandler(void);
void WEAK DMA_CH9_IRQHandler(void);
void WEAK DMA_CH10_IRQHandler(void);
void WEAK DMA_CH11_IRQHandler(void);
void WEAK DMA_CH12_IRQHandler(void);
void WEAK DMA_CH13_IRQHandler(void);
void WEAK DMA_CH14_IRQHandler(void);
void WEAK DMA_CH15_IRQHandler(void);
void WEAK DMA_CH16_IRQHandler(void);
void WEAK DMA_CH17_IRQHandler(void);
void WEAK DMA_CH18_IRQHandler(void);
void WEAK DMA_CH19_IRQHandler(void);
void WEAK DMA_CH20_IRQHandler(void);
void WEAK DMA_CH21_IRQHandler(void);
void WEAK DMA_CH22_IRQHandler(void);
void WEAK DMA_CH23_IRQHandler(void);
void WEAK DMA_CH24_IRQHandler(void);
void WEAK DMA_CH25_IRQHandler(void);
void WEAK DMA_CH26_IRQHandler(void);
void WEAK DMA_CH27_IRQHandler(void);
void WEAK DMA_CH28_IRQHandler(void);
void WEAK DMA_CH29_IRQHandler(void);
void WEAK DMA_CH30_IRQHandler(void);
void WEAK DMA_CH31_IRQHandler(void);
void WEAK TMR0_IRQHandler(void);
void WEAK TMR1_IRQHandler(void);
void WEAK TMR2_IRQHandler(void);
void WEAK TMR3_IRQHandler(void);
void WEAK ETMR0_IRQHandler(void);
void WEAK ETMR1_IRQHandler(void);
void WEAK ETMR2_IRQHandler(void);
void WEAK ETMR3_IRQHandler(void);
void WEAK UART0_TD_IRQHandler(void);
void WEAK UART0_MS_IRQHandler(void);
void WEAK UART0_RX_IRQHandler(void);
void WEAK UART0_TX_IRQHandler(void);
void WEAK UART0_RT_IRQHandler(void);
void WEAK UART0_E_IRQHandler(void);
void WEAK UART0_IRQHandler(void);
void WEAK UART1_TD_IRQHandler(void);
void WEAK UART1_MS_IRQHandler(void);
void WEAK UART1_RX_IRQHandler(void);
void WEAK UART1_TX_IRQHandler(void);
void WEAK UART1_RT_IRQHandler(void);
void WEAK UART1_E_IRQHandler(void);
void WEAK UART1_IRQHandler(void);
void WEAK UART2_TD_IRQHandler(void);
void WEAK UART2_MS_IRQHandler(void);
void WEAK UART2_RX_IRQHandler(void);
void WEAK UART2_TX_IRQHandler(void);
void WEAK UART2_RT_IRQHandler(void);
void WEAK UART2_E_IRQHandler(void);
void WEAK UART2_IRQHandler(void);
void WEAK UART3_TD_IRQHandler(void);
void WEAK UART3_MS_IRQHandler(void);
void WEAK UART3_RX_IRQHandler(void);
void WEAK UART3_TX_IRQHandler(void);
void WEAK UART3_RT_IRQHandler(void);
void WEAK UART3_E_IRQHandler(void);
void WEAK UART3_IRQHandler(void);
void WEAK TUART0_RX_IRQHandler(void);
void WEAK TUART0_TX_IRQHandler(void);
void WEAK TUART0_RO_IRQHandler(void);
void WEAK TUART0_TO_IRQHandler(void);
void WEAK TUART0_IRQHandler(void);
void WEAK TUART1_RX_IRQHandler(void);
void WEAK TUART1_TX_IRQHandler(void);
void WEAK TUART1_RO_IRQHandler(void);
void WEAK TUART1_TO_IRQHandler(void);
void WEAK TUART1_IRQHandler(void);
void WEAK SPI0_IRQHandler(void);
void WEAK SPI0_RX_IRQHandler(void);
void WEAK SPI0_TX_IRQHandler(void);
void WEAK SPI0_RO_IRQHandler(void);
void WEAK SPI0_RT_IRQHandler(void);
void WEAK SPI1_IRQHandler(void);
void WEAK SPI1_RX_IRQHandler(void);
void WEAK SPI1_TX_IRQHandler(void);
void WEAK SPI1_RO_IRQHandler(void);
void WEAK SPI1_RT_IRQHandler(void);
void WEAK SPI2_IRQHandler(void);
void WEAK SPI2_RX_IRQHandler(void);
void WEAK SPI2_TX_IRQHandler(void);
void WEAK SPI2_RO_IRQHandler(void);
void WEAK SPI2_RT_IRQHandler(void);
void WEAK SPI3_IRQHandler(void);
void WEAK SPI3_RX_IRQHandler(void);
void WEAK SPI3_TX_IRQHandler(void);
void WEAK SPI3_RO_IRQHandler(void);
void WEAK SPI3_RT_IRQHandler(void);
void WEAK I2C0_IRQHandler(void);
void WEAK I2C1_IRQHandler(void);
void WEAK SPWR0_IRQHandler(void);
void WEAK SPWR1_IRQHandler(void);
void WEAK MILSTD0_IRQHandler(void);
void WEAK MILSTD1_IRQHandler(void);
void WEAK ECAP0_IRQHandler(void);
void WEAK ECAP1_IRQHandler(void);
void WEAK ECAP2_IRQHandler(void);
void WEAK ECAP3_IRQHandler(void);
void WEAK ECAP4_IRQHandler(void);
void WEAK ECAP5_IRQHandler(void);
void WEAK PWM0_IRQHandler(void);
void WEAK PWM0_HD_IRQHandler(void);
void WEAK PWM0_TZ_IRQHandler(void);
void WEAK PWM1_IRQHandler(void);
void WEAK PWM1_HD_IRQHandler(void);
void WEAK PWM1_TZ_IRQHandler(void);
void WEAK PWM2_IRQHandler(void);
void WEAK PWM2_HD_IRQHandler(void);
void WEAK PWM2_TZ_IRQHandler(void);
void WEAK PWM3_IRQHandler(void);
void WEAK PWM3_HD_IRQHandler(void);
void WEAK PWM3_TZ_IRQHandler(void);
void WEAK PWM4_IRQHandler(void);
void WEAK PWM4_HD_IRQHandler(void);
void WEAK PWM4_TZ_IRQHandler(void);
void WEAK PWM5_IRQHandler(void);
void WEAK PWM5_HD_IRQHandler(void);
void WEAK PWM5_TZ_IRQHandler(void);
void WEAK PWM6_IRQHandler(void);
void WEAK PWM6_HD_IRQHandler(void);
void WEAK PWM6_TZ_IRQHandler(void);
void WEAK PWM7_IRQHandler(void);
void WEAK PWM7_HD_IRQHandler(void);
void WEAK PWM7_TZ_IRQHandler(void);
void WEAK PWM8_IRQHandler(void);
void WEAK PWM8_HD_IRQHandler(void);
void WEAK PWM8_TZ_IRQHandler(void);
void WEAK PWM9_IRQHandler(void);
void WEAK PWM9_HD_IRQHandler(void);
void WEAK PWM9_TZ_IRQHandler(void);
void WEAK QEP0_IRQHandler(void);
void WEAK QEP1_IRQHandler(void);
void WEAK QEP2_IRQHandler(void);
void WEAK QEP3_IRQHandler(void);
void WEAK ADC_SEQ0_IRQHandler(void);
void WEAK ADC_SEQ1_IRQHandler(void);
void WEAK ADC_SEQ2_IRQHandler(void);
void WEAK ADC_SEQ3_IRQHandler(void);
void WEAK ADC_SEQ4_IRQHandler(void);
void WEAK ADC_SEQ5_IRQHandler(void);
void WEAK ADC_SEQ6_IRQHandler(void);
void WEAK ADC_SEQ7_IRQHandler(void);
void WEAK ADC_DC_IRQHandler(void);
void WEAK ETH_IRQHandler(void);
void WEAK CAN0_IRQHandler(void);
void WEAK CAN1_IRQHandler(void);
void WEAK CAN2_IRQHandler(void);
void WEAK CAN3_IRQHandler(void);
void WEAK CAN4_IRQHandler(void);
void WEAK CAN5_IRQHandler(void);
void WEAK CAN6_IRQHandler(void);
void WEAK CAN7_IRQHandler(void);
void WEAK CAN8_IRQHandler(void);
void WEAK CAN9_IRQHandler(void);
void WEAK CAN10_IRQHandler(void);
void WEAK CAN11_IRQHandler(void);
void WEAK CAN12_IRQHandler(void);
void WEAK CAN13_IRQHandler(void);
void WEAK CAN14_IRQHandler(void);
void WEAK CAN15_IRQHandler(void);
void WEAK FPU_IRQHandler(void);
void WEAK TMU_IRQHandler(void);
void WEAK LAU_IRQHandler(void);
void WEAK SDFM_IRQHandler(void);
void WEAK OWI0_IRQHandler(void);
void WEAK OWI1_IRQHandler(void);

typedef struct {
/*----------Core Exceptions-----------------------------------------------------*/
	void (*_estack)(void);	
	void (*Reset_Handler)(void);
	void (*NMI_Handler)(void);
	void (*HardFault_Handler)(void);
	void (*MemManage_Handler)(void);
	void (*BusFault_Handler)(void);
	void (*UsageFault_Handler)(void);
	void (*Reserved1)(void);
	void (*Reserved2)(void);
	void (*Reserved3)(void);
	void (*Reserved4)(void);
	void (*SVC_Handler)(void);
	void (*DebugMon_Handler)(void);
	void (*Reserved5)(void);
	void (*PendSV_Handler)(void);
	void (*SysTick_Handler)(void);
/*----------External Exceptions-----------------------------------------------*/
	void (*WDT_IRQHandler)(void);
	void (*RCU_IRQHandler)(void);
	void (*RTC_IRQHandler)(void);
	void (*MFLASH_IRQHandler)(void);
	void (*BFLASH_IRQHandler)(void);
	void (*GPIOA_IRQHandler)(void);
	void (*GPIOB_IRQHandler)(void);
	void (*GPIOC_IRQHandler)(void);
	void (*GPIOD_IRQHandler)(void);
	void (*GPIOE_IRQHandler)(void);
	void (*GPIOF_IRQHandler)(void);
	void (*GPIOG_IRQHandler)(void);
	void (*GPIOH_IRQHandler)(void);
	void (*GPIOJ_IRQHandler)(void);
	void (*GPIOK_IRQHandler)(void);
	void (*GPIOL_IRQHandler)(void);
	void (*GPIOM_IRQHandler)(void);
	void (*DMA_CH0_IRQHandler)(void);
	void (*DMA_CH1_IRQHandler)(void);
	void (*DMA_CH2_IRQHandler)(void);
	void (*DMA_CH3_IRQHandler)(void);
	void (*DMA_CH4_IRQHandler)(void);
	void (*DMA_CH5_IRQHandler)(void);
	void (*DMA_CH6_IRQHandler)(void);
	void (*DMA_CH7_IRQHandler)(void);
	void (*DMA_CH8_IRQHandler)(void);
	void (*DMA_CH9_IRQHandler)(void);
	void (*DMA_CH10_IRQHandler)(void);
	void (*DMA_CH11_IRQHandler)(void);
	void (*DMA_CH12_IRQHandler)(void);
	void (*DMA_CH13_IRQHandler)(void);
	void (*DMA_CH14_IRQHandler)(void);
	void (*DMA_CH15_IRQHandler)(void);
	void (*DMA_CH16_IRQHandler)(void);
	void (*DMA_CH17_IRQHandler)(void);
	void (*DMA_CH18_IRQHandler)(void);
	void (*DMA_CH19_IRQHandler)(void);
	void (*DMA_CH20_IRQHandler)(void);
	void (*DMA_CH21_IRQHandler)(void);
	void (*DMA_CH22_IRQHandler)(void);
	void (*DMA_CH23_IRQHandler)(void);
	void (*DMA_CH24_IRQHandler)(void);
	void (*DMA_CH25_IRQHandler)(void);
	void (*DMA_CH26_IRQHandler)(void);
	void (*DMA_CH27_IRQHandler)(void);
	void (*DMA_CH28_IRQHandler)(void);
	void (*DMA_CH29_IRQHandler)(void);
	void (*DMA_CH30_IRQHandler)(void);
	void (*DMA_CH31_IRQHandler)(void);
	void (*TMR0_IRQHandler)(void);
	void (*TMR1_IRQHandler)(void);
	void (*TMR2_IRQHandler)(void);
	void (*TMR3_IRQHandler)(void);
	void (*ETMR0_IRQHandler)(void);
	void (*ETMR1_IRQHandler)(void);
	void (*ETMR2_IRQHandler)(void);
	void (*ETMR3_IRQHandler)(void);
	void (*UART0_TD_IRQHandler)(void);
	void (*UART0_MS_IRQHandler)(void);
	void (*UART0_RX_IRQHandler)(void);
	void (*UART0_TX_IRQHandler)(void);
	void (*UART0_RT_IRQHandler)(void);
	void (*UART0_E_IRQHandler)(void);
	void (*UART0_IRQHandler)(void);
	void (*UART1_TD_IRQHandler)(void);
	void (*UART1_MS_IRQHandler)(void);
	void (*UART1_RX_IRQHandler)(void);
	void (*UART1_TX_IRQHandler)(void);
	void (*UART1_RT_IRQHandler)(void);
	void (*UART1_E_IRQHandler)(void);
	void (*UART1_IRQHandler)(void);
	void (*UART2_TD_IRQHandler)(void);
	void (*UART2_MS_IRQHandler)(void);
	void (*UART2_RX_IRQHandler)(void);
	void (*UART2_TX_IRQHandler)(void);
	void (*UART2_RT_IRQHandler)(void);
	void (*UART2_E_IRQHandler)(void);
	void (*UART2_IRQHandler)(void);
	void (*UART3_TD_IRQHandler)(void);
	void (*UART3_MS_IRQHandler)(void);
	void (*UART3_RX_IRQHandler)(void);
	void (*UART3_TX_IRQHandler)(void);
	void (*UART3_RT_IRQHandler)(void);
	void (*UART3_E_IRQHandler)(void);
	void (*UART3_IRQHandler)(void);
	void (*TUART0_RX_IRQHandler)(void);
	void (*TUART0_TX_IRQHandler)(void);
	void (*TUART0_RO_IRQHandler)(void);
	void (*TUART0_TO_IRQHandler)(void);
	void (*TUART0_IRQHandler)(void);
	void (*TUART1_RX_IRQHandler)(void);
	void (*TUART1_TX_IRQHandler)(void);
	void (*TUART1_RO_IRQHandler)(void);
	void (*TUART1_TO_IRQHandler)(void);
	void (*TUART1_IRQHandler)(void);
	void (*SPI0_IRQHandler)(void);
	void (*SPI0_RX_IRQHandler)(void);
	void (*SPI0_TX_IRQHandler)(void);
	void (*SPI0_RO_IRQHandler)(void);
	void (*SPI0_RT_IRQHandler)(void);
	void (*SPI1_IRQHandler)(void);
	void (*SPI1_RX_IRQHandler)(void);
	void (*SPI1_TX_IRQHandler)(void);
	void (*SPI1_RO_IRQHandler)(void);
	void (*SPI1_RT_IRQHandler)(void);
	void (*SPI2_IRQHandler)(void);
	void (*SPI2_RX_IRQHandler)(void);
	void (*SPI2_TX_IRQHandler)(void);
	void (*SPI2_RO_IRQHandler)(void);
	void (*SPI2_RT_IRQHandler)(void);
	void (*SPI3_IRQHandler)(void);
	void (*SPI3_RX_IRQHandler)(void);
	void (*SPI3_TX_IRQHandler)(void);
	void (*SPI3_RO_IRQHandler)(void);
	void (*SPI3_RT_IRQHandler)(void);
	void (*I2C0_IRQHandler)(void);
	void (*I2C1_IRQHandler)(void);
	void (*SPWR0_IRQHandler)(void);
	void (*SPWR1_IRQHandler)(void);
	void (*MILSTD0_IRQHandler)(void);
	void (*MILSTD1_IRQHandler)(void);
	void (*ECAP0_IRQHandler)(void);
	void (*ECAP1_IRQHandler)(void);
	void (*ECAP2_IRQHandler)(void);
	void (*ECAP3_IRQHandler)(void);
	void (*ECAP4_IRQHandler)(void);
	void (*ECAP5_IRQHandler)(void);
	void (*PWM0_IRQHandler)(void);
	void (*PWM0_HD_IRQHandler)(void);
	void (*PWM0_TZ_IRQHandler)(void);
	void (*PWM1_IRQHandler)(void);
	void (*PWM1_HD_IRQHandler)(void);
	void (*PWM1_TZ_IRQHandler)(void);
	void (*PWM2_IRQHandler)(void);
	void (*PWM2_HD_IRQHandler)(void);
	void (*PWM2_TZ_IRQHandler)(void);
	void (*PWM3_IRQHandler)(void);
	void (*PWM3_HD_IRQHandler)(void);
	void (*PWM3_TZ_IRQHandler)(void);
	void (*PWM4_IRQHandler)(void);
	void (*PWM4_HD_IRQHandler)(void);
	void (*PWM4_TZ_IRQHandler)(void);
	void (*PWM5_IRQHandler)(void);
	void (*PWM5_HD_IRQHandler)(void);
	void (*PWM5_TZ_IRQHandler)(void);
	void (*PWM6_IRQHandler)(void);
	void (*PWM6_HD_IRQHandler)(void);
	void (*PWM6_TZ_IRQHandler)(void);
	void (*PWM7_IRQHandler)(void);
	void (*PWM7_HD_IRQHandler)(void);
	void (*PWM7_TZ_IRQHandler)(void);
	void (*PWM8_IRQHandler)(void);
	void (*PWM8_HD_IRQHandler)(void);
	void (*PWM8_TZ_IRQHandler)(void);
	void (*PWM9_IRQHandler)(void);
	void (*PWM9_HD_IRQHandler)(void);
	void (*PWM9_TZ_IRQHandler)(void);
	void (*QEP0_IRQHandler)(void);
	void (*QEP1_IRQHandler)(void);
	void (*QEP2_IRQHandler)(void);
	void (*QEP3_IRQHandler)(void);
	void (*ADC_SEQ0_IRQHandler)(void);
	void (*ADC_SEQ1_IRQHandler)(void);
	void (*ADC_SEQ2_IRQHandler)(void);
	void (*ADC_SEQ3_IRQHandler)(void);
	void (*ADC_SEQ4_IRQHandler)(void);
	void (*ADC_SEQ5_IRQHandler)(void);
	void (*ADC_SEQ6_IRQHandler)(void);
	void (*ADC_SEQ7_IRQHandler)(void);
	void (*ADC_DC_IRQHandler)(void);
	void (*ETH_IRQHandler)(void);
	void (*CAN0_IRQHandler)(void);
	void (*CAN1_IRQHandler)(void);
	void (*CAN2_IRQHandler)(void);
	void (*CAN3_IRQHandler)(void);
	void (*CAN4_IRQHandler)(void);
	void (*CAN5_IRQHandler)(void);
	void (*CAN6_IRQHandler)(void);
	void (*CAN7_IRQHandler)(void);
	void (*CAN8_IRQHandler)(void);
	void (*CAN9_IRQHandler)(void);
	void (*CAN10_IRQHandler)(void);
	void (*CAN11_IRQHandler)(void);
	void (*CAN12_IRQHandler)(void);
	void (*CAN13_IRQHandler)(void);
	void (*CAN14_IRQHandler)(void);
	void (*CAN15_IRQHandler)(void);
	void (*FPU_IRQHandler)(void);
	void (*TMU_IRQHandler)(void);
	void (*LAU_IRQHandler)(void);
	void (*SDFM_IRQHandler)(void);
	void (*OWI0_IRQHandler)(void);
	void (*OWI1_IRQHandler)(void);	
} ISRVectorsTables;

/*@}*/
